import type { PlayerObject } from "../src/model";
import { PlayerAnimation } from "../src/animation";

/**
 * Simple example animation. This could be generated by an external tool.
 * The player slowly spins around the Y axis.
 */
export class GeneratedAnimation extends PlayerAnimation {
	protected animate(player: PlayerObject, delta: number): void {
		player.rotation.y += delta;
	}
}
